### ISSUE TITLE
Should the browse work or is it in progress?

### ISSUE THREAD

**Issue by biancode** [fh1ch/node-bacstack-browser#2]
Hi Fabio,

The browser does not work with the Yabe DemoServer. 

<img width="1287" alt="grafik" src="https://user-images.githubusercontent.com/4369867/36351762-e6730b20-14ae-11e8-9566-ff6bc02f7f74.png">

I have the same problem with reading  by bacstack lib function readProperty - I got at every read "Error: BacnetError - Class:5 - Code:67"

Thank you!
Klaus

**Comment by biancode** [comment]
<img width="1266" alt="grafik" src="https://user-images.githubusercontent.com/4369867/36351839-8cd80312-14af-11e8-92e0-20a2f7a3faa5.png">

<img width="1266" alt="grafik" src="https://user-images.githubusercontent.com/4369867/36351842-93d5ff52-14af-11e8-9970-2b2c1eb9a6be.png">

**Comment by biancode** [comment]
https://sourceforge.net/projects/yetanotherbacnetexplorer/

**Comment by fh1ch** [comment]
Hi @biancode 

First of all, thank you very much for your interest into this topic any contributions in form of issue reports 👍 

**Regarding the state of this project:** It is an extreme early prototype of mine which I sadly couldn't invest much time and shall therefore not be considered as stable. However, I'm already use it occasionally and certainly want to develop it further, especially since there isn't a proper BACNET browser for Mac OSX...

**Regarding the issue you experience:** The error code you provided can be decoded using the following lines (https://github.com/fh1ch/node-bacstack/blob/master/lib/enum.js#L104 / https://github.com/fh1ch/node-bacstack/blob/master/lib/enum.js#L118). In you case this is: "Service: Unrecognised Service". This is the case when the BACNET server doesn't support the `readPropertyMultiple` function, which is required for full generic browsing. The YABE browser has a fallback mode for this case and has in general better error handling, which is completely inexistent in this project at this point in time. One of the next steps of this project would exactly to support such cases and especially improve the error handling.

I hope this already answers your questions. Feel free to re-open this issue otherwise.

Cheers
Fabio

**Comment by biancode** [comment]
@fh1ch what is your server for testing, please? I see some localhost operations in the tests.

**Comment by fh1ch** [comment]
I mainly used https://github.com/fh1ch/node-bacstack-device for the work on this project while being on the road. Otherwise, I mainly use real BACNET/BTL certified test devices in my networks.

On the node-bacstack project I also started to write some compliance tests (see https://github.com/fh1ch/node-bacstack/blob/test/compliance-tests/Dockerfile.device) based on `bacnet-stack` (C++ edition), which looks quiet good on first sight.
